files:
  include:
    - ./resources/sass/**/*.scss
rules:
  shorthand-values:
    - 1
    - allowed-shorthands:
        - 1
        - 2
  max-file-line-count:
    - 1
    -
      length: 1000
  indentation:
    - 1
    -
      size: 'tab'
  no-color-keywords: 0
  no-color-literals: 0
  property-sort-order: 0
  leading-zero: 0
  nesting-depth: 0
  class-name-format: 0
  variable-name-format: 0
  no-css-comments: 0
  mixins-before-declarations: 0
  border-zero: 0
  force-pseudo-nesting: 0
  no-empty-rulesets: 0
  force-element-nesting: 0
  no-vendor-prefixes: 0
  hex-length: 0
  no-qualifying-elements: 0
